- name: outside the variables file
  hosts: local
  connection: local
  vars_files:
    course.yaml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello {{course}}, duration is {{duration}}, trainer: {{charan}}"

