- name: outside the variables file
  hosts: local
  connection: local
  vars:
    course: AWS
    duration: 120hrs
    trainer: charan
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello {{course}}, duration is {{duration}}, trainer: {{trainer}}"

