- name: playing loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: doing loops
      ansible.builtin.package:
         name: "{{ item }}"
         state: installed

      loops:
      - nginx
      - sql
      
    