- name: playing loops
  hosts: localhost
  connection: localhost
  tasks:
  - name: doing loops
    ansible.builtin.package:
      - name: "{{ item }}"
        state: installed

    loops:
    - nginx
    - sql
      
    